sudo: enable
language: go
git:
    depth: 1
branches:
  only:
    - master
install:
    - sudo apt install -y tree
script:
    - pwd
    - ls /home/travis/gopath/src/whalecold/compress/pkg/command
    - echo $GOPATH
    - tree pkg
    - make build
